name: master
on:
  push:
    branches:
      - master
env:
    docker_username: ${{ github.actor }}
    docker_password: ${{ secrets.GITHUB_TOKEN }}
    GIT_COMMIT: ${{ github.sha }}

jobs:
    Docker-image-backend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: replace whitespace with hyphen
              run: echo "NAME=$(echo ${{github.repository}} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
            - name: Build Docker image
              run: |
                docker build . --tag ghcr.io/${{ env.NAME }}:latest
                docker push ghcr.io/${{ env.NAME }}:latest
